import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "DMARC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" href="/assets/icons/favicon.ico" sizes="any" />
    </head>
    <body className={poppins.className}>
      <div className="w-30 bg-gray-400 p-5 m-5">
      {children}
      </div>
      </body>
  </html>
  );
}
